import type { RoadmapStep } from "../components/RoadmapDetailPage";

export type RoadmapConfig = {
  badge: string;
  title: string;
  subtitle: string;
  steps: RoadmapStep[];
};

const icons = {
  blue: "/roadmap-icons/typescript_3d_code_icon.svg",
  dark: "/roadmap-icons/next_3d_code_icon.svg",
  green: "/roadmap-icons/quality_3d_code_icon.svg",
  html: "/roadmap-icons/html5_3d_code_icon.svg",
  js: "/roadmap-icons/javascript_3d_code_icon.svg",
  react: "/roadmap-icons/react_3d_code_icon.svg",
};

export const roadmaps: Record<string, RoadmapConfig> = {
  frontend: {
    badge: "Frontend roadmap",
    title: "Frontend Developer Roadmap",
    subtitle: "A modern path from web fundamentals to production-ready frontend apps.",
    steps: [
      {
        eyebrow: "Foundation",
        title: "HTML, CSS & JavaScript",
        description: "Build the page structure, visual styling, and interactive behavior users touch first.",
        icon: icons.html,
        color: "#0ea5e9",
        glow: "shadow-sky-200",
        skills: ["Semantic HTML", "CSS layouts", "JavaScript basics"],
      },
      {
        eyebrow: "Workflow",
        title: "Git & DevTools",
        description: "Track changes, inspect the browser, debug issues, and understand how pages behave.",
        icon: icons.js,
        color: "#f59e0b",
        glow: "shadow-amber-200",
        skills: ["Git", "Browser DevTools", "Debugging"],
      },
      {
        eyebrow: "Experience",
        title: "Responsive, A11y & UX",
        description: "Create interfaces that adapt to screens, work for more people, and feel clear to use.",
        icon: icons.blue,
        color: "#7c3aed",
        glow: "shadow-violet-200",
        skills: ["Responsive UI", "Accessibility", "UX basics"],
      },
    ],
  },
  backend: {
    badge: "Backend roadmap",
    title: "Backend Developer Roadmap",
    subtitle: "Build secure APIs, data systems, and scalable server-side products.",
    steps: [
      {
        eyebrow: "Language",
        title: "Pick a Backend Language",
        description: "Start with one server language and learn how packages, runtime, and tooling work.",
        icon: icons.js,
        color: "#f59e0b",
        glow: "shadow-amber-200",
        skills: ["Node.js or Python", "Package managers", "Git"],
      },
      {
        eyebrow: "Data",
        title: "Databases & CRUD",
        description: "Store application data, model relationships, and practice reliable CRUD flows.",
        icon: icons.blue,
        color: "#2563eb",
        glow: "shadow-blue-200",
        skills: ["PostgreSQL", "SQL basics", "CRUD"],
      },
      {
        eyebrow: "Services",
        title: "APIs, Auth & Scale",
        description: "Expose server behavior through APIs, protect users, and prepare services for traffic.",
        icon: icons.dark,
        color: "#111827",
        glow: "shadow-slate-200",
        skills: ["REST APIs", "Authentication", "Performance"],
      },
    ],
  },
  "full-stack": {
    badge: "Full stack roadmap",
    title: "Full Stack Developer Roadmap",
    subtitle: "Connect frontend, backend, databases, and deployment into complete products.",
    steps: [
      {
        eyebrow: "Frontend",
        title: "UI Foundations",
        description: "Turn designs into accessible interfaces with HTML, CSS, JavaScript, and a framework.",
        icon: icons.html,
        color: "#0ea5e9",
        glow: "shadow-sky-200",
        skills: ["HTML/CSS", "JavaScript", "React or Vue"],
      },
      {
        eyebrow: "Backend",
        title: "Server & Database",
        description: "Write business logic, manage data access, and design APIs that the UI can consume.",
        icon: icons.blue,
        color: "#7c3aed",
        glow: "shadow-violet-200",
        skills: ["Node.js or Python", "SQL/NoSQL", "REST APIs"],
      },
      {
        eyebrow: "Product",
        title: "Integration & Release",
        description: "Use Git, debugging, deployment, and small projects to ship full-featured web apps.",
        icon: icons.green,
        color: "#10b981",
        glow: "shadow-emerald-200",
        skills: ["Git", "Deployment", "Portfolio projects"],
      },
    ],
  },
  devops: {
    badge: "DevOps roadmap",
    title: "DevOps Roadmap",
    subtitle: "Automate delivery, operate infrastructure, and improve system reliability.",
    steps: [
      {
        eyebrow: "Core",
        title: "Linux, Git & Scripting",
        description: "Build the practical foundation for automation and day-to-day operations work.",
        icon: icons.dark,
        color: "#111827",
        glow: "shadow-slate-200",
        skills: ["Linux", "Git", "Python/Bash"],
      },
      {
        eyebrow: "Delivery",
        title: "CI/CD & Containers",
        description: "Automate build, test, and release flows using pipelines and container workflows.",
        icon: icons.js,
        color: "#f59e0b",
        glow: "shadow-amber-200",
        skills: ["CI/CD", "Docker", "Kubernetes"],
      },
      {
        eyebrow: "Operations",
        title: "Cloud, IaC & Observability",
        description: "Manage cloud infrastructure, codify environments, and monitor production behavior.",
        icon: icons.green,
        color: "#10b981",
        glow: "shadow-emerald-200",
        skills: ["AWS/Azure/GCP", "Terraform", "Monitoring"],
      },
    ],
  },
  mobile: {
    badge: "Mobile roadmap",
    title: "Mobile Developer Roadmap",
    subtitle: "Create app experiences for phones, tablets, stores, and device ecosystems.",
    steps: [
      {
        eyebrow: "Platform",
        title: "Choose iOS, Android, or Cross-Platform",
        description: "Start with one ecosystem and learn its language, UI model, and tooling.",
        icon: icons.blue,
        color: "#2563eb",
        glow: "shadow-blue-200",
        skills: ["Kotlin", "Swift", "React Native"],
      },
      {
        eyebrow: "App UX",
        title: "Screens, State & Device APIs",
        description: "Build navigation, forms, state, offline flows, notifications, and device integrations.",
        icon: icons.react,
        color: "#06b6d4",
        glow: "shadow-cyan-200",
        skills: ["Navigation", "State", "Device APIs"],
      },
      {
        eyebrow: "Release",
        title: "Testing & Store Delivery",
        description: "Test on devices, optimize performance, and prepare releases for app stores.",
        icon: icons.green,
        color: "#10b981",
        glow: "shadow-emerald-200",
        skills: ["Testing", "Performance", "App stores"],
      },
    ],
  },
  "ai-engineer": {
    badge: "AI engineer roadmap",
    title: "AI Engineer Roadmap",
    subtitle: "Apply models and AI tools to build practical, useful product experiences.",
    steps: [
      {
        eyebrow: "Foundation",
        title: "Programming & Data Basics",
        description: "Use Python, APIs, and data handling to prepare inputs and integrate AI features.",
        icon: icons.blue,
        color: "#2563eb",
        glow: "shadow-blue-200",
        skills: ["Python", "APIs", "Data handling"],
      },
      {
        eyebrow: "Models",
        title: "LLMs, Prompts & RAG",
        description: "Work with pre-trained models, prompt workflows, embeddings, and retrieval patterns.",
        icon: icons.dark,
        color: "#111827",
        glow: "shadow-slate-200",
        skills: ["LLMs", "Prompting", "RAG"],
      },
      {
        eyebrow: "Production",
        title: "Evaluation & Product Safety",
        description: "Measure outputs, improve reliability, and ship AI features with guardrails.",
        icon: icons.green,
        color: "#10b981",
        glow: "shadow-emerald-200",
        skills: ["Evaluation", "Monitoring", "Safety"],
      },
    ],
  },
  "data-engineer": {
    badge: "Data engineer roadmap",
    title: "Data Engineer Roadmap",
    subtitle: "Move, model, and operate data so teams can trust analytics and products.",
    steps: [
      {
        eyebrow: "Core",
        title: "SQL, Python & Data Modeling",
        description: "Learn the language of data systems and how to shape raw data into useful structures.",
        icon: icons.blue,
        color: "#2563eb",
        glow: "shadow-blue-200",
        skills: ["SQL", "Python", "Data modeling"],
      },
      {
        eyebrow: "Pipelines",
        title: "Batch, Streaming & Orchestration",
        description: "Build reliable flows that ingest, transform, schedule, and validate data.",
        icon: icons.js,
        color: "#f59e0b",
        glow: "shadow-amber-200",
        skills: ["ETL/ELT", "Airflow", "Streaming"],
      },
      {
        eyebrow: "Platform",
        title: "Warehouses & Cloud Data",
        description: "Operate warehouses, lakes, permissions, observability, and cost-aware data platforms.",
        icon: icons.green,
        color: "#10b981",
        glow: "shadow-emerald-200",
        skills: ["Warehouse", "Cloud", "Governance"],
      },
    ],
  },
  "cyber-security": {
    badge: "Cyber security roadmap",
    title: "Cyber Security Roadmap",
    subtitle: "Understand systems, find weaknesses, and protect users, networks, and applications.",
    steps: [
      {
        eyebrow: "Basics",
        title: "Networking, Linux & Web",
        description: "Understand the systems attackers and defenders both rely on every day.",
        icon: icons.dark,
        color: "#111827",
        glow: "shadow-slate-200",
        skills: ["Networking", "Linux", "HTTP"],
      },
      {
        eyebrow: "Security",
        title: "Threats, AppSec & Identity",
        description: "Learn vulnerabilities, authentication, authorization, and secure design habits.",
        icon: icons.html,
        color: "#ef4444",
        glow: "shadow-red-200",
        skills: ["OWASP", "Identity", "Threat modeling"],
      },
      {
        eyebrow: "Operations",
        title: "Monitoring & Incident Response",
        description: "Detect suspicious behavior, investigate incidents, and improve defenses over time.",
        icon: icons.green,
        color: "#10b981",
        glow: "shadow-emerald-200",
        skills: ["SIEM", "Logs", "Incident response"],
      },
    ],
  },
  qa: {
    badge: "QA roadmap",
    title: "QA Engineer Roadmap",
    subtitle: "Build confidence in releases through testing strategy, automation, and quality systems.",
    steps: [
      {
        eyebrow: "Testing",
        title: "Quality Fundamentals",
        description: "Learn test types, bug reports, acceptance criteria, and exploratory testing.",
        icon: icons.green,
        color: "#10b981",
        glow: "shadow-emerald-200",
        skills: ["Test cases", "Bug reports", "Exploratory testing"],
      },
      {
        eyebrow: "Automation",
        title: "Web & API Automation",
        description: "Automate repeatable checks across interfaces, APIs, and user workflows.",
        icon: icons.react,
        color: "#06b6d4",
        glow: "shadow-cyan-200",
        skills: ["Playwright", "API tests", "CI checks"],
      },
      {
        eyebrow: "Release",
        title: "Performance & Release Confidence",
        description: "Use metrics, regression suites, and risk analysis to support safer releases.",
        icon: icons.js,
        color: "#f59e0b",
        glow: "shadow-amber-200",
        skills: ["Regression", "Performance", "Risk analysis"],
      },
    ],
  },
};
